Repository salesforce-ux/slds-linter, pull requests merged in 2025-05, with the labels that each got.

#158 chore: fixing build scripts for workspaces
  .gitignore
  .yarnrc.yml
  package.json
  packages/cli/package.json
  packages/eslint-plugin-slds/package.json
  packages/stylelint-plugin-slds/package.json
  yarn.lock
Labels: chore

#156 @W-18491606 : Use SLDS Linter as a node API
  .gitignore
  .yarnrc.yml
  package.json
  packages/cli/README.md
  packages/cli/examples/README.md
  packages/cli/examples/node-api-example.mjs
  packages/cli/examples/test-api/README.md
  packages/cli/examples/test-api/api-test.js
  packages/cli/package.json
  packages/cli/src/commands/emit.ts
  packages/cli/src/commands/lint.ts
  packages/cli/src/commands/report.ts
  packages/cli/src/executor/__tests__/executor.test.ts
  packages/cli/src/executor/index.ts
  packages/cli/src/services/report-generator.ts
  packages/cli/src/types/index.ts
  packages/cli/src/utils/cli-args.ts
  packages/cli/src/utils/config-utils.ts
  packages/eslint-plugin-slds/package.json
  packages/stylelint-plugin-slds/package.json
  scripts/validate-sarif.js
  yarn.lock
Labels: ready-for-review, requested-changes, Don't Merge Yet

#162 @W-18549731: Release Script Fix for Yarn Workspace Changes
  package.json
  packages/cli/package.json
  packages/eslint-plugin-slds/package.json
  packages/stylelint-plugin-slds/package.json
  scripts/release.js
  yarn.lock
Labels: released, v0.2.0-alpha.2
